import Link from "next/link";

export function DifyTutorial() {
  return (
    <article className="guide">
      <p className="text-muted-foreground text-sm tracking-[0.2em]">DIFY · ORACLE · MINIMAX</p>
      <h1 className="font-heading mt-3 text-3xl leading-tight md:text-5xl">
        用 Dify + Oracle + MiniMax 搭翻译助手
      </h1>
      <p className="text-muted-foreground mt-4 text-sm leading-7">
        对着 Alfred Zhao 那篇教材做，只把 DeepSeek 换成 MiniMax。下面按真实点击顺序写，从装环境到跑通两个用例。
      </p>

      <nav className="not-prose mt-6 rounded-2xl bg-[color:var(--sheet)] px-5 py-4 text-sm ring-1 ring-foreground/10">
        <p className="mb-2 text-xs tracking-widest text-[color:var(--seal)]">目录</p>
        <ol className="grid gap-1 sm:grid-cols-2">
          <li>0. 先看懂流水线</li>
          <li>1. 准备三样东西</li>
          <li>2. 在 Oracle 建术语表和函数</li>
          <li>3. 打开或自建 Dify</li>
          <li>4. 接入 MiniMax</li>
          <li>5. 接入 Oracle 插件</li>
          <li>6. 编排四节点工作流</li>
          <li>7. 用两个用例验收</li>
          <li>8. 发布和排错</li>
        </ol>
      </nav>

      <section>
        <h2>0. 先看懂流水线</h2>
        <p>工作流只要四步，不要做复杂：</p>
        <ol>
          <li>
            <strong>开始</strong>：用户贴一段英文。
          </li>
          <li>
            <strong>Oracle 查询</strong>：调用 <code>match_english_terms()</code>，从术语表抽出命中词。
          </li>
          <li>
            <strong>LLM</strong>：把原文 + 术语清单交给 MiniMax-M3。
          </li>
          <li>
            <strong>结束</strong>：只输出译文。另外可以再挂一个调试出口，专门看术语抽对没有。
          </li>
        </ol>
        <p>
          原教材用 DeepSeek。MiniMax 只替换 LLM 节点，Oracle 表、函数、Dify 连线都一样。
        </p>
      </section>

      <section>
        <h2>1. 准备三样东西</h2>
        <h3>1.1 MiniMax Key</h3>
        <ol>
          <li>
            国内账号打开{" "}
            <a href="https://platform.minimaxi.com/user-center/payment/token-plan" target="_blank" rel="noreferrer">
              platform.minimaxi.com
            </a>
            ，国际账号用{" "}
            <a href="https://platform.minimax.io/user-center/basic-information/interface-key" target="_blank" rel="noreferrer">
              platform.minimax.io
            </a>
            。两套账号和 Key 不能混用。
          </li>
          <li>复制 API Key / 订阅 Key。国内常见前缀是 <code>sk-cp-</code>。</li>
          <li>确认账户有余额或 Token Plan，否则 Dify 里会报无 choices / 鉴权失败。</li>
        </ol>

        <h3>1.2 Oracle 库</h3>
        <p>任选一种能被 Dify 访问的库：</p>
        <ul>
          <li>已有 Oracle 19c / 23ai / Autonomous。</li>
          <li>
            个人练习可用 23ai Free 容器，默认服务名 <code>FREEPDB1</code>，端口 <code>1521</code>：
          </li>
        </ul>
        <pre>{`docker run -d --name oracle-free -p 1521:1521 \\
  -e ORACLE_PWD=ChangeMe_123 \\
  container-registry.oracle.com/database/free:latest`}</pre>
        <p>
          第一次启动要等几分钟，直到日志出现数据库就绪。记下 host、端口、用户、密码、service name。
        </p>

        <h3>1.3 Dify</h3>
        <p>两种走法：</p>
        <ul>
          <li>
            最快：打开{" "}
            <a href="https://cloud.dify.ai" target="_blank" rel="noreferrer">
              cloud.dify.ai
            </a>
            注册。后面插件和市场步骤一样。
          </li>
          <li>要数据在自己机器上：本机 Docker 部署（下一步）。</li>
        </ul>
        <p>自托管最低大约 2 核 CPU、4 GB 内存；Compose 需要 2.24.0 以上。</p>
        <pre>{`git clone --branch "$(curl -s https://api.github.com/repos/langgenius/dify/releases/latest | jq -r .tag_name)" https://github.com/langgenius/dify.git
cd dify/docker
cp .env.example .env
docker compose up -d
docker compose ps`}</pre>
        <p>
          浏览器打开 <code>http://localhost/install</code> 建管理员，再登录 <code>http://localhost</code>。
          如果克隆时报 branch 为 null，到{" "}
          <a href="https://github.com/langgenius/dify/releases" target="_blank" rel="noreferrer">
            Dify Releases
          </a>{" "}
          抄一个版本号，改成 <code>git clone --branch v1.x.x ...</code>。
        </p>
      </section>

      <section>
        <h2>2. 在 Oracle 建术语表和函数</h2>
        <p>
          用 SQL*Plus、SQLcl、SQL Developer 或 VS Code Oracle 插件，连上目标 schema，依次执行仓库里的{" "}
          <code>sql/01_create_glossary.sql</code> 和 <code>sql/02_match_english_terms.sql</code>。
        </p>
        <h3>2.1 建表并插入教材三条术语</h3>
        <pre>{`CREATE TABLE glossary (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term           VARCHAR2(200) NOT NULL,
    translation    VARCHAR2(500) NOT NULL,
    domain         VARCHAR2(50) DEFAULT 'TEST' NOT NULL,
    note           VARCHAR2(500),
    CONSTRAINT glossary_uk UNIQUE (term, domain)
);

INSERT INTO glossary(term, translation) VALUES ('Oracle','甲骨文中国');
INSERT INTO glossary(term, translation) VALUES ('Exadata Database Machine','原厂Exadata数据库一体机');
INSERT INTO glossary(term, translation) VALUES ('Oracle Database Appliance','原厂ODA数据库一体机');
COMMIT;`}</pre>

        <h3>2.2 建匹配函数</h3>
        <p>
          原教材用 <code>REGEXP_LIKE</code> 扫表。这里补了 <code>ORDER BY LENGTH(term) DESC</code>，避免短词
          Oracle 抢在产品全称前面。
        </p>
        <pre>{`CREATE OR REPLACE FUNCTION match_english_terms(
    p_input IN VARCHAR2
) RETURN VARCHAR2 IS
    v_result CLOB := '';
BEGIN
    FOR rec IN (
        SELECT term, translation
        FROM glossary
        WHERE REGEXP_LIKE(p_input, '(^|\\W)' || term || '(\\W|$)', 'i')
        ORDER BY LENGTH(term) DESC, term
    ) LOOP
        v_result := v_result
            || '英文: ' || rec.term
            || '; 中文: ' || rec.translation
            || CHR(10);
    END LOOP;

    IF v_result IS NULL OR LENGTH(v_result) = 0 THEN
        RETURN '（未命中术语）';
    END IF;
    IF LENGTH(v_result) > 4000 THEN
        RETURN SUBSTR(v_result, 1, 4000);
    END IF;
    RETURN v_result;
EXCEPTION
    WHEN OTHERS THEN
        RETURN '错误: ' || SQLERRM;
END match_english_terms;
/`}</pre>

        <h3>2.3 在库里先自检，再接到 Dify</h3>
        <pre>{`SELECT match_english_terms(
  'Oracle Exadata Database Machine is powerful.'
) FROM dual;

SELECT match_english_terms(
  'Oracle Database Appliance delivers exceptional cost-effectiveness for enterprise database workloads.'
) FROM dual;`}</pre>
        <p>第一条应同时出现 Oracle 和 Exadata Database Machine。第二条应出现完整的 Oracle Database Appliance，不要只剩一个 Oracle。</p>
      </section>

      <section>
        <h2>3. 打开 Dify 工作台</h2>
        <ol>
          <li>登录后进入「工作室」。</li>
          <li>先不要建应用。先把模型和数据库插件装好，工作流里才选得到。</li>
        </ol>
      </section>

      <section>
        <h2>4. 接入 MiniMax（替换原教材的 DeepSeek）</h2>
        <p>
          官方写法见 MiniMax「其他工具」文档里的 Dify 一节。国内推荐走 Anthropic 兼容地址。
        </p>
        <ol>
          <li>
            右上角进 <strong>设置 → 工作空间 → 模型供应商</strong>（有的版本叫「模型供应商」或 Integrations）。
          </li>
          <li>
            搜索 <strong>Minimax</strong>，安装官方插件 <code>langgenius/minimax</code>。
          </li>
          <li>点「添加 API Key / Setup」。</li>
          <li>按区域填：</li>
        </ol>
        <div className="overflow-x-auto">
          <table>
            <thead>
              <tr>
                <th>字段</th>
                <th>国内</th>
                <th>国际</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>API Key</td>
                <td>minimaxi.com 的订阅 Key</td>
                <td>minimax.io 的 Key</td>
              </tr>
              <tr>
                <td>API Base / endpoint</td>
                <td>
                  <code>https://api.minimaxi.com/anthropic</code>
                </td>
                <td>
                  <code>https://api.minimax.io/anthropic</code>
                </td>
              </tr>
              <tr>
                <td>Group ID</td>
                <td colSpan={2}>留空。M3 / M2.x 不需要；只有老 ABAB / Embedding / TTS 才用</td>
              </tr>
              <tr>
                <td>模型</td>
                <td colSpan={2}>
                  <code>MiniMax-M3</code>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>保存后，在供应商卡片上应能看到 MiniMax-M3 可用。可先随便建一个聊天应用，发「只回复：就绪」做连通性测试。</p>

        <h3>备用接法：OpenAI 兼容供应商</h3>
        <p>如果官方 Minimax 插件装不上，或模型列表是空的：</p>
        <ol>
          <li>模型供应商里找 <strong>OpenAI-API-compatible</strong>。</li>
          <li>
            Base URL 填 <code>https://api.minimaxi.com/v1</code>（国际改 <code>https://api.minimax.io/v1</code>）。注意不要写成 <code>.../v1/v1</code>。
          </li>
          <li>
            模型名手填 <code>MiniMax-M3</code>，API Key 同上。
          </li>
        </ol>
      </section>

      <section>
        <h2>5. 接入 Oracle 插件</h2>
        <p>
          原教材截图用的是 <code>db_query</code>。现在市场里对应的官方工具是{" "}
          <strong>Oracle AI Database</strong>（<code>langgenius/oracle_ai_db</code>），Thin Mode，Dify 机器不用装 Instant Client。
        </p>
        <ol>
          <li>
            打开{" "}
            <a href="https://marketplace.dify.ai/plugin/langgenius/oracle_ai_db" target="_blank" rel="noreferrer">
              Marketplace · Oracle AI Database
            </a>
            ，或在 Dify「工具 / 插件」里搜索 Oracle。
          </li>
          <li>安装后，工作流里可以拖「Query」工具节点（只做 SELECT / 函数调用）。</li>
          <li>连接参数这样填：</li>
        </ol>
        <div className="overflow-x-auto">
          <table>
            <thead>
              <tr>
                <th>参数</th>
                <th>示例</th>
                <th>注意</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>host</td>
                <td>
                  <code>192.168.1.20</code> 或 <code>host.docker.internal</code>
                </td>
                <td>Dify 在 Docker 里时，不要写 <code>127.0.0.1</code>，那是容器自己</td>
              </tr>
              <tr>
                <td>port</td>
                <td>
                  <code>1521</code>
                </td>
                <td>Autonomous 常见 1522</td>
              </tr>
              <tr>
                <td>user / password</td>
                <td>建表用的那个 schema</td>
                <td>不要用 SYS。给普通用户 <code>CREATE SESSION</code> 和表、函数权限即可</td>
              </tr>
              <tr>
                <td>service_name</td>
                <td>
                  <code>FREEPDB1</code> / <code>ORCLPDB1</code> / Autonomous 的 xxx_low
                </td>
                <td>这是 service name，不是 SID</td>
              </tr>
              <tr>
                <td>query</td>
                <td>见下一步 SQL</td>
                <td>输出格式先选 Text-Markdown 或 JSON，调试更直观</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          云上 Autonomous 若必须钱包，确认插件是否支持 mTLS；个人练习用 23ai Free 或已开通 TCP 的 PDB 更省事。
          安全组 / 防火墙要放行 Dify 所在机器访问 1521。
        </p>
      </section>

      <section>
        <h2>6. 编排工作流（对着点）</h2>
        <ol>
          <li>
            工作室右上角 <strong>创建应用 → 工作流 Workflow</strong>。不要选「聊天助手」，这个场景是一问一译，不需要多轮记忆。
          </li>
          <li>应用名例如「术语翻译助手」。</li>
          <li>进入编排画布后，按下面四个节点配。</li>
        </ol>

        <h3>节点 A · 开始 START</h3>
        <ol>
          <li>点开始节点，添加输入变量。</li>
          <li>
            变量名：<code>user_input</code>（后面 SQL 和提示词都引用它，不要用中文名）。
          </li>
          <li>类型：段落 / 长文本。</li>
          <li>必填：打开。</li>
          <li>标签可以写「待翻译原文」。</li>
        </ol>

        <h3>节点 B · Oracle Query</h3>
        <ol>
          <li>从工具栏加「Oracle AI Database / Query」，接到开始节点后面。</li>
          <li>填 host、port、user、password、service_name。</li>
          <li>
            query 里不要手写死原文，用变量选择器插入 <code>user_input</code>。最终 SQL 应等价于：
          </li>
        </ol>
        <pre>{`SELECT match_english_terms('{{user_input}}') AS text FROM dual`}</pre>
        <p>
          界面里变量看起来会像 <code>{"{{#1740000000000.user_input#}}"}</code>，那是节点 ID，用选择器插入即可，不要手抄别人的 ID。
        </p>
        <p>
          输出格式建议先选 <strong>Text-Markdown</strong>，后面提示词更好读。记住这个节点的输出字段名，常见是 <code>text</code>。
        </p>
        <p>
          原文里如果有英文单引号，直接拼进 SQL 会断句。验收先用教材两句（没有撇号）。要处理撇号，可在 SQL 外包一层{" "}
          <code>REPLACE(..., '''', '''''')</code>，或先加一个代码节点做转义。
        </p>

        <h3>节点 C · LLM（选 MiniMax-M3）</h3>
        <ol>
          <li>加「LLM」节点，接到 Query 后面。</li>
          <li>模型选 <strong>MiniMax / MiniMax-M3</strong>。</li>
          <li>温度 0.2～0.3。翻译要稳，不要开到 1。</li>
          <li>如果有 thinking / 推理开关，先关掉，译文更干净、也更快。</li>
          <li>上下文、记忆都关掉。</li>
        </ol>
        <p>系统提示（SYSTEM）：</p>
        <pre>{`你是一个专业的技术文档翻译助手，能够识别指定术语并严格替换，同时将非术语部分自然翻译，最终组合成流畅的中文。
请优先匹配最长术语。
只输出最终译文，不要解释，不要标题，不要备注。`}</pre>
        <p>用户提示（USER），用变量选择器插入「原文」和「术语结果」：</p>
        <pre>{`请将以下英文内容翻译为中文：
{{user_input}}

需要替换的术语如下：
{{sql_query.text}}`}</pre>
        <p>
          <code>{"{{sql_query.text}}"}</code> 只是示意。以你画布上 Query 节点的实际输出变量为准，点一下插入。
        </p>

        <h3>节点 D · 结束 END</h3>
        <ol>
          <li>结束节点输出选 LLM 的 <code>text</code> / 回复。</li>
          <li>
            再复制一个结束节点当调试口（教材里的 END2）：输出改成 Query 节点的术语文本。跑不通时先看这个口，确认数据库有没有抽到词。
          </li>
        </ol>
        <p>整条线应是：开始 → Query → LLM → 结束；Query 再分一条到「术语调试」结束节点。</p>
      </section>

      <section>
        <h2>7. 用两个用例验收</h2>
        <p>点右上角「预览 / 运行」，业务域不用填，函数默认扫 glossary 表。</p>
        <div className="overflow-x-auto">
          <table>
            <thead>
              <tr>
                <th>输入</th>
                <th>调试口应看到</th>
                <th>译文里必须出现</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>Oracle Exadata Database Machine is powerful.</td>
                <td>Oracle → 甲骨文中国；Exadata Database Machine → 原厂Exadata数据库一体机</td>
                <td>甲骨文中国、原厂Exadata数据库一体机</td>
              </tr>
              <tr>
                <td>Oracle Database Appliance delivers exceptional cost-effectiveness for enterprise database workloads.</td>
                <td>Oracle Database Appliance → 原厂ODA数据库一体机（不要先拆成 Oracle）</td>
                <td>原厂ODA数据库一体机</td>
              </tr>
            </tbody>
          </table>
        </div>
        <p>
          如果模型又在译文后面加「说明：」，回到系统提示，强调「只输出最终译文」。这是原教材里已经踩过的点。
        </p>
      </section>

      <section>
        <h2>8. 发布，以及常见卡点</h2>
        <h3>发布</h3>
        <ol>
          <li>预览通过后点「发布」。</li>
          <li>「运行」页可以当内部工具给同事用。</li>
          <li>
            「访问 API」里拿 Key。自托管请求打到你的 Dify 域名，云端是 <code>https://api.dify.ai/v1/workflows/run</code>。
          </li>
        </ol>
        <pre>{`curl -X POST 'https://你的Dify/v1/workflows/run' \\
  -H 'Authorization: Bearer app-xxxx' \\
  -H 'Content-Type: application/json' \\
  -d '{
    "inputs": {
      "user_input": "Oracle Exadata Database Machine is powerful."
    },
    "response_mode": "blocking",
    "user": "aria"
  }'`}</pre>
        <p>
          <code>inputs</code> 的 key 必须和开始节点变量名完全一致。
        </p>

        <h3>排错</h3>
        <ul>
          <li>
            <strong>MiniMax 401 / 无 choices</strong>：国内 Key 配了国际地址，或反过来。Group ID 被填了垃圾值。账户没额度。
          </li>
          <li>
            <strong>Oracle 连不上</strong>：host 写成了 127.0.0.1；Docker 网络不通；service name 和 SID 搞反；安全组没放行。
          </li>
          <li>
            <strong>函数返回「错误: ...」</strong>：函数没编译成功。在库里单独 <code>SELECT match_english_terms(&apos;Oracle&apos;) FROM dual</code>。
          </li>
          <li>
            <strong>只匹配到 Oracle，ODA 被拆开</strong>：函数缺少按长度排序，或术语表里没有完整产品名。
          </li>
          <li>
            <strong>LLM 没用术语</strong>：用户提示没把 Query 输出插进去，或插的是开始节点而不是 SQL 结果。
          </li>
          <li>
            <strong>SQL 报引号错误</strong>：原文含 <code>&apos;</code>。先用教材例句验收，再补转义。
          </li>
        </ul>
      </section>

      <section>
        <h2>和这个网页版的关系</h2>
        <p>
          <Link href="/">对词</Link> 把同一条流水线收进了浏览器：术语表在{" "}
          <code>data/glossary.json</code>，匹配在 <code>src/lib/glossary.ts</code>，模型仍是 MiniMax。
          适合一个人先验证术语。要给同事维护 Oracle 表、用 Dify 发布 API，就按本页搭。
        </p>
        <p>
          原理短文在 <Link href="/guide">教材</Link>。原博客：
          <a
            href="https://www.cnblogs.com/jyzhao/p/19054638/shou-ba-shou-jiao-ni-da-zao-yi-ge-geng-dong-ni-dea"
            target="_blank"
            rel="noreferrer"
          >
            手把手教你打造一个更懂你的AI翻译助手
          </a>
          。
        </p>
      </section>
    </article>
  );
}
