-- 术语表：同一业务域内 term 唯一
CREATE TABLE glossary (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    term           VARCHAR2(200) NOT NULL,
    translation    VARCHAR2(500) NOT NULL,
    domain         VARCHAR2(50) DEFAULT 'TEST' NOT NULL,
    note           VARCHAR2(500),
    CONSTRAINT glossary_uk UNIQUE (term, domain)
);

INSERT INTO glossary(term, translation, domain, note) VALUES
    ('Oracle', '甲骨文中国', 'TEST', '教材用例：验证品牌名会被强制改写');
INSERT INTO glossary(term, translation, domain, note) VALUES
    ('Exadata Database Machine', '原厂Exadata数据库一体机', 'TEST', '教材用例：最长术语优先');
INSERT INTO glossary(term, translation, domain, note) VALUES
    ('Oracle Database Appliance', '原厂ODA数据库一体机', 'TEST', '教材用例：避免先匹配到 Oracle');
COMMIT;
